name: yamagatabank_flutter
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluro: ^1.5.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  webview_flutter: ^0.3.15+1
  dio: 3.0.7
  flustars: ^0.2.6+1
  sqflite: ^1.1.0
  #数据库
  flutter_swiper: ^1.1.6
  #轮播
  shared_preferences: ^0.5.4+3
  #本地缓存
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/
    - images/ic_record.png
    - images/ic_banking.png
    - images/ic_atm.png
    - images/town_selected.png
    - images/ic_record_click.png
    - images/ic_banking_clicked.png
    - images/ic_atm_clicked.png
    - images/town_selected.png
    - images/balance_default.png
    - images/splash.gif
    - images/guidepage_1.png
    - images/guidepage_2.png
    - images/guidepage_3.png
    - images/guidepage_4.png
    - images/guidepage_5.png
    - images/ic_error.png
    - images/new_normal.png
    - images/new_selected.png
    - images/gourmet_selected.png
    - images/gourmet_normal.png
    - images/event_normal.png
    - images/event_selected.png
    - images/trip_selected.png
    - images/trip_normal.png
    - images/life_normal.png
    - images/life_selected.png
    - images/work_selected.png
    - images/work_normal.png
    - images/special_normal.png
    - images/special_selected.png
    - images/icon_new.png