name: minefocus_base_flutter
description: minefocus
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 网络请求
  dio: ^2.1.13
  # 获取设备信息
  device_info : ^0.4.0+2
  # 获取APP信息
  package_info: ^0.4.0+6
  # json转model
  dart_json_mapper:  ^1.1.11
  # 字典存储
  shared_preferences: ^0.5.3+4
  # keychain存储
  flutter_secure_storage: ^3.3.1
  # 字符串加密
  encrypt: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
