import '../DetailsPage/cost_detail_item.dart';


List<CostDetailModel> newsList = [
	CostDetailModel(
		mYear: "2019",
		mMonth: "7",
		mDay: "1",
		mCostType: 1,
		mCostDetail: "デビッド(VISA-000111)",
		mDescribe: "備品を購入",
		mCost: 100.0,
		mIncomeTotalCost: 100.0,
		mOutlayTotalCost: 200.0,
	),
	CostDetailModel(
		mYear: "2019",
		mMonth: "7",
		mDay: "2",
		mCostType: 2,
		mCostDetail: "カード",
		mDescribe: "",
		mCost: 100.0,
		mIncomeTotalCost: 100.0,
		mOutlayTotalCost: 200.0,
	),
	CostDetailModel(
		mYear: "2019",
		mMonth: "7",
		mDay: "29",
		mCostType: 1,
		mCostDetail: "収入（サトウ　ハナコ）",
		mDescribe: "",
		mCost: 100.0,
		mIncomeTotalCost: 100.0,
		mOutlayTotalCost: 200.0,
	),
	CostDetailModel(
		mYear: "2019",
		mMonth: "7",
		mDay: "30",
		mCostType: 1,
		mCostDetail: "カード",
		mDescribe: "旅行代金として父から受領",
		mCost: 100.0,
		mIncomeTotalCost: 100.0,
		mOutlayTotalCost: 200.0,
	),
	CostDetailModel(
		mYear: "2019",
		mMonth: "8",
		mDay: "1",
		mCostType: 2,
		mCostDetail: "口座振替（ABC生命保険）",
		mDescribe: "",
		mCost: 100.0,
		mIncomeTotalCost: 100.0,
		mOutlayTotalCost: 200.0,
	),
	CostDetailModel(
		mYear: "2019",
		mMonth: "8",
		mDay: "3",
		mCostType: 2,
		mCostDetail: "給与振入（株式会社AAA）",
		mDescribe: "",
		mCost: 100.0,
		mIncomeTotalCost: 100.0,
		mOutlayTotalCost: 200.0,
	),
	CostDetailModel(
		mYear: "2019",
		mMonth: "8",
		mDay: "25",
		mCostType: 1,
		mCostDetail: "カード",
		mDescribe: "給料を入って",
		mCost: 100.0,
		mIncomeTotalCost: 100.0,
		mOutlayTotalCost: 200.0,
	),
	CostDetailModel(
		mYear: "2019",
		mMonth: "8",
		mDay: "28",
		mCostType: 1,
		mCostDetail: "カード",
		mDescribe: "映画のチケット",
		mCost: 100.0,
		mIncomeTotalCost: 100.0,
		mOutlayTotalCost: 200.0,
	),
	CostDetailModel(
		mYear: "2019",
		mMonth: "9",
		mDay: "30",
		mCostType: 2,
		mCostDetail: "カード",
		mDescribe: "晩ご飯の費用",
		mCost: 100.0,
		mIncomeTotalCost: 100.0,
		mOutlayTotalCost: 200.0,
	),
];